import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoginBtn from "./loginButton";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <LoginBtn />
        </nav>
        {children}
      </body>
    </html>
  );
}
